version: '3'

services:
    composer:
        volumes:
            - ./composer.json:/app/composer.json
            - ./composer.lock:/app/composer.lock
            - vendor:/app/vendor
    cli:
        volumes:
            - ./:/srv/orcid-dummy
            - /srv/orcid-dummy/build
            - vendor:/srv/orcid-dummy/vendor

volumes:
    vendor:
